author: Nuno Aguiar
scripts:
  posterase: ''
  postinstall: |
    log("Pushover: on openaf-console type help pushover");
    log("Slack   : on openaf-console type help slack");
  preerase: ''
  preinstall: ''
keywords:
- notifications
- push
- pushover
- slack
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  backurl: https://raw.githubusercontent.com/OpenAF/openaf-opacks/master/Notifications
  url: https://openaf.io/opacks/Notifications.opack
description: Provides libraries to use notifications services. Currently pushover.js.
name: Notifications
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20250925'
dependencies:
  openaf: '>=20241117'
files:
- .odoc.db
- .package.yaml
- .precompile
- README.md
- mcp-notify.yaml
- msteams.js
- notificationsPushover.yaml
- notificationsSlack.yaml
- pushover.js
- slack.js
filesHash:
  .odoc.db: bccc183a8df3aebb9a9d894604dda29bdc23416c
  .precompile: 296680c7a954da9eb871b3c3ee40ff7fba58ee5d
  README.md: 4c1216a263188bc9337700d7f0524f3d75530eb0
  mcp-notify.yaml: cd9597c9e0ec47736a3371d49d7351ada3aedeb3
  msteams.js: 36226eb5297c2941799c9abd53c33e815ef0491b
  notificationsPushover.yaml: c4fbfb5f947bd2f5b7c1d1ca3bd7bd45a06eaec5
  notificationsSlack.yaml: d2e206929861cecf3fb9844255f69734b2906d0a
  pushover.js: a183d24a29956d69e96b01323e8769cdc3ae6c2d
  slack.js: 4256a6fe055b7f68f7dc2a55c494b4beca14cbce
