author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: if (Number(ow.format.getJavaVersion().replace(/^1\./, "").replace(/(\d+).*/, "$1")) < 11) throw("Only supported Java >= 11")
  postinstall: ''
keywords:
- openaf
- git
- plugins
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  url: https://openaf.io/opacks/plugin-GIT.opack
description: OpenAF plugin to access GIT repositories.
name: plugin-GIT
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260418'
dependencies:
  openaf: '>=20230704'
files:
- .maven.yaml
- .odoc.db
- .package.yaml
- JavaEWAH-1.2.3.jar
- README.md
- compile.yaml
- org.eclipse.jgit-7.6.0.202603022253-r.jar
- plugin-git.jar
- src/openaf/plugins/GIT.class
- src/openaf/plugins/GIT.java
filesHash:
  .maven.yaml: 36161a963e6b2b726d04cadcd87c031e22acdb04
  .odoc.db: e8103b29125f38e06251f0df0bbfa07ad699f0ba
  JavaEWAH-1.2.3.jar: 13a27c856e0c8808cee9a64032c58eee11c3adc9
  README.md: 3c52f958f88b7bcea305a37c1f3f25d6680776c7
  compile.yaml: 8cba5f4eac9724a275b3c9f1484ae8bc3f950cc2
  org.eclipse.jgit-7.6.0.202603022253-r.jar: 1c6d9f63581d24c9a7d9c50a6dbe6ab6df13dc0f
  plugin-git.jar: 0864309847d48c46e65666c31775052fa1ec2a2c
  src/openaf/plugins/GIT.class: d7d5caf6148eeea0a006d923101b4c940cd0d52f
  src/openaf/plugins/GIT.java: 07dfe293e47804f434c22ef1013a3ee6ec798e11
