author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- debug
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  url: https://openaf.io/opacks/Debug.opack
description: Debug wrapper functionality to transform comments into active debugging
name: Debug
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20220127'
dependencies:
  OpenAF: '>=20220127'
files:
- .package.yaml
- README.md
- debug.js
- debug.yaml
- debugFn.js
filesHash:
  README.md: bbd92d2513f10870f2df25b7b65c31691133b51d
  debug.js: 7653310132d7b82733575bf587fe93050efece4b
  debug.yaml: d3b8a3be266057902930d99ca4e36860b4d8d369
  debugFn.js: f1322d6ed7938a222c3cd875f340619e93ef5974
