author: Nuno Aguiar
scripts:
  posterase: ''
  postinstall: ''
  preerase: ''
  preinstall: ''
keywords: []
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  backurl: https://raw.githubusercontent.com/OpenAF/openaf-opacks/master/XChart
  url: https://openaf.io/opacks/XChart.opack
description: Provides a wrapper to use the XChart java charts library. Allows the creation of png (or others) images of charts and html/css inline images of charts.
name: XChart
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260524'
dependencies: {}
files:
- .odoc.db
- .package.yaml
- .precompile
- README.md
- lib/.maven.yaml
- lib/LICENSE
- lib/VectorGraphics2D-0.13.jar
- lib/animated-gif-lib-1.4.jar
- lib/apiguardian-api-1.1.2.jar
- lib/commons-logging-1.3.5.jar
- lib/fontbox-3.0.5.jar
- lib/graphics2d-3.0.5.jar
- lib/pdfbox-3.0.5.jar
- lib/pdfbox-io-3.0.5.jar
- lib/xchart-4.0.0.jar
- test/test.html
- xchart.js
filesHash:
  .odoc.db: c1f8cc5cf6ec6ddfb40d5e0c00b502a4f5847381
  .precompile: 385bd4e4b141d74d6074c035ba192d8acadf2c24
  README.md: ce0369b9c7a1323320afee6eef30de5a325a184c
  lib/.maven.yaml: d4c601d7ee214535c35c6e791aad55d425dd16ec
  lib/LICENSE: 3809b4e8be6b906334959cac98d49bb09e6ba93f
  lib/VectorGraphics2D-0.13.jar: f1ad944da4c6b6a27d244d3a04ce1c67b8b026b6
  lib/animated-gif-lib-1.4.jar: b6ab3aa0a27499b6677153ebd59bbecb7ae8af41
  lib/apiguardian-api-1.1.2.jar: a231e0d844d2721b0fa1b238006d15c6ded6842a
  lib/commons-logging-1.3.5.jar: a3fcc5d3c29b2b03433aa2d2f2d2c1b1638924a1
  lib/fontbox-3.0.5.jar: b4a068e1dba2b9832a108cdf6e9a3249680e3ce8
  lib/graphics2d-3.0.5.jar: 150de966a74960e1672cca36fc638e0ee9a20bc3
  lib/pdfbox-3.0.5.jar: c34109061c3a0d85d871d9edc469ac0682f81856
  lib/pdfbox-io-3.0.5.jar: 402151a8d1aa427ea879cc7160e9227e9f5088ba
  lib/xchart-4.0.0.jar: d91dd2e1a21fb56ae23ee077fb8f70a980e4eda6
  test/test.html: bd8103c4c6c487039e082d1189abb03058067c8d
  xchart.js: 6b77fb260ab9548e50bdeec92a93434eb00cc536
