author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- ssh
- server
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  url: https://openaf.io/opacks/SSHd.opack
description: A SSH server implementation
name: SSHd
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260805'
dependencies:
  openaf: '>=20240812'
files:
- .maven.yaml
- .odoc.db
- .package.yaml
- README.md
- jcl-over-slf4j-1.7.36.jar
- sshd-common-2.19.0.jar
- sshd-core-2.19.0.jar
- sshd.js
filesHash:
  .maven.yaml: ee0f29c0f33f7f1d12702a35f85608037d9e91ce
  .odoc.db: 88d56dd8174b836f3d33d3c897d0553588c64dd4
  README.md: 672a0f1976636ccb8c59c04be649b1f461f38a9b
  jcl-over-slf4j-1.7.36.jar: d877e195a05aca4a2f1ad2ff14bfec1393af4b5e
  sshd-common-2.19.0.jar: 5f871c9c88ba810d6ac21b14a1279c1fce21d5b2
  sshd-core-2.19.0.jar: e1524d99feece8d50db0a75f43f99818c649dd97
  sshd.js: e259c0eb5ad9cafee480cd36143605f1c2670ef0
