author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- aws
- lambda
- layers
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  url: https://openaf.io/opacks/OpenAFLambdaLayers.opack
description: Build AWS Lambda layers or a compatible OpenAF container build context
name: OpenAFLambdaLayers
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260921'
dependencies:
  openaf: '>=20220822'
files:
- .package.yaml
- Dockerfile
- Dockerfile.container
- Dockerfile.lambda
- README.md
- bootstrap
- bootstrap.container
- build.yaml
- dockerignore.container
- lambda.js
- lambda.orig.js
- main.js.example
filesHash:
  Dockerfile: d32f9358f88dac21b90055c0c7a044c8cc5c91d5
  Dockerfile.container: f06e6df09ffb08d6fd449dfc983d2b1cde109cc5
  Dockerfile.lambda: feb2169b375f60a26347e5383c6812a64963794c
  README.md: 2782b713740b06a839cff5acb6a09ba3a989a020
  bootstrap: a945e2603fb5d5b0233dd8cdc0e85f423fc2646c
  bootstrap.container: 37e934d34be976f2661fd646ddbea112a24eaf19
  build.yaml: e0062803c9796569e09ddd945d47c08beca30bff
  dockerignore.container: 64676640f60802832280c64b1cc6b6aa94ff1de0
  lambda.js: 0dfcab8d4ac30a5a48f02598caecc2d53f3667d9
  lambda.orig.js: c80deab9d69979e70229acc47c9feaf95e48a29a
  main.js.example: bec6dc9e3b149d9de3617ad0f50c39801c9095b5
