#!/bin/sh
set -euo pipefail
export OAF_HOME=/tmp
/opt/jre/bin/java -Xshare:off -XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport -XX:MinRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0 -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -Djava.system.class.loader=openaf.OAFdCL -jar /opt/openaf/openaf.jar -f /opt/lambda.js