author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://mariadb.com/kb/en/about-mariadb-connector-j. To use it just: loadLib(\"jdbc-mariadb.js\"); var db = new DB(\"jdbc:mariadb://{{host}}:{{port}}/{{database}}\", ...) ");'
keywords:
- DB
- JDBC
- mariadb
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of mariadb
name: jdbc-mariadb
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260613'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- jdbc-mariadb.js
- mariadb-java-client-3.5.9.jar
filesHash:
  LICENSES.txt: f2d42a124bd65ef477c9626d4f07abbd8469cb02
  jdbc-mariadb.js: aaeac058daddb2884ccf5a3b4cf1d5a2f11970f2
  mariadb-java-client-3.5.9.jar: 69e11e3cf29d42088d3fcf689c313079b52d6277
