author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: print("Please remove \"loadLib(\"inBrowser.js\");\" from your ~/.openaf-console_profile or c:/users/myuser/.openaf-console_profile.");
  preinstall: ''
  postinstall: print("Please add \"loadLib(\"inBrowser.js\");\" to your ~/.openaf-console_profile or c:/users/myuser/.openaf-console_profile.");
keywords:
- ace
- editor
- inBrowser
- browser
- watch
- show
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  url: https://openaf.io/opacks/inBrowser.opack
description: Provides a mini browser editor intended to use from openaf-console to edit objects or perform show/watch in a browser window.
name: inBrowser
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260920'
dependencies:
  openaf: '>=20180507'
files:
- .odoc.db
- .package.yaml
- .precompile
- README.md
- docs/chart-example.png
- docs/example1.png
- docs/example2.png
- docs/right-click.png
- docs/table-example.png
- gui/_ace/ace.zip
- gui/_css/font/context-menu-icons.eot
- gui/_css/font/context-menu-icons.ttf
- gui/_css/font/context-menu-icons.woff
- gui/_css/font/context-menu-icons.woff2
- gui/_css/jquery.contextMenu.min.css
- gui/_images/openaf.ico
- gui/_images/openaf.png
- gui/_js/Chart.bundle.min.js
- gui/_js/jquery.contextMenu.min.js
- gui/_js/jquery.ui.position.min.js
- gui/licenses/ACE-LICENSE
- gui/licenses/CHARTJS-LICENSE
- gui/licenses/CONTEXTMENU-LICENSE
- gui/licenses/JQUERYUI-LICENSE
- inBrowser.hbs
- inBrowser.js
- upstream.json
filesHash:
  .odoc.db: 26bd5f82b68542f997ef27600446e8365a425088
  .precompile: 3e4ff6370cb69cf1ecdc99d9da3ca180c566021c
  README.md: cbd38daf4962220e7a24d186bf1179fdd427623e
  docs/chart-example.png: 3b4646ef09e9d57e7a3813af915cbde6bec3670a
  docs/example1.png: b9127b290381313da1bc7913a79ea58a74b767b1
  docs/example2.png: b7684b94a4f5c11d09b8b04ef5a9f0df8998d5cd
  docs/right-click.png: 96488e59a63b8a1b740a7fa7bbf7f75fa313a428
  docs/table-example.png: 716faf901fe6db5cbf7036c8a6eaff5db3ea4891
  gui/_ace/ace.zip: cb70983711d44c0d45850a1dbe42216f8a426328
  gui/_css/font/context-menu-icons.eot: 1e0bb220f690ece26b2b1dd1fc176d735f5ff2ed
  gui/_css/font/context-menu-icons.ttf: 8e715cb910cdcee5a6d773bd537ce83398eb4b6f
  gui/_css/font/context-menu-icons.woff: 735bda06350f5e6df883c43dce16554d434d0e60
  gui/_css/font/context-menu-icons.woff2: be029e5d3316dc3af3acdad5361ae448dc965aba
  gui/_css/jquery.contextMenu.min.css: bb8bdc38a915b180c51c06609765b21535494375
  gui/_images/openaf.ico: 544d110dcb3ba387ea206011ede749f51393b134
  gui/_images/openaf.png: 2287f19313c67b8c7b0952fe501fcc199ff4fc2b
  gui/_js/Chart.bundle.min.js: 304d5742ff744fb950a3e8bfc26226539e97a67f
  gui/_js/jquery.contextMenu.min.js: 5bc48ace88d5fd92c0e91773c75ea631adec6390
  gui/_js/jquery.ui.position.min.js: 2ea42888a1d6d9a569821e4e48e974455812bc70
  gui/licenses/ACE-LICENSE: bd077e65d4090e7db560d16dac1255ee36297c66
  gui/licenses/CHARTJS-LICENSE: 6a190f7891b160f2319ea2f2f001e469843e9a55
  gui/licenses/CONTEXTMENU-LICENSE: e2497d015856c0693f35afc3b303b443e14fcbb2
  gui/licenses/JQUERYUI-LICENSE: d5d70a29df19925f574a44a6e90a9d4dd1b96733
  inBrowser.hbs: a8770e252cad7a7c4eb15fe567020662c3b8ccf2
  inBrowser.js: 16fc209be97d3460335cf375b25413d1e2052d65
  upstream.json: 088132b926df29dbf47cceb3939e30c38f7507aa
