author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://github.com/duckdb/duckdb-java. To use it just: loadLib(\"jdbc-duckdb.js\"); var db = new DB(\"jdbc:duckdb:{{file}}\", ...) ");'
keywords:
- DB
- JDBC
- duckdb
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of duckdb
name: jdbc-duckdb
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260324'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- duckdb_jdbc-1.5.1.0.jar
- jdbc-duckdb.js
filesHash:
  LICENSES.txt: e166ea95384dfd6ed8bd73f9dffc7097e720f943
  duckdb_jdbc-1.5.1.0.jar: 01a648f0081497e5d97d24dece3d8bd6a5bd2b2f
  jdbc-duckdb.js: 45ca00f4dfdd4b10c4e89657773d1cb5c68d0e43
