author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://github.com/duckdb/duckdb-java. To use it just: loadLib(\"jdbc-duckdb.js\"); var db = new DB(\"jdbc:duckdb:{{file}}\", ...) ");'
keywords:
- DB
- JDBC
- duckdb
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of duckdb
name: jdbc-duckdb
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260807'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- duckdb_jdbc-1.5.5.1.jar
- jdbc-duckdb.js
filesHash:
  LICENSES.txt: a405f7d34a586e65d7fb38a17101b380a876be02
  duckdb_jdbc-1.5.5.1.jar: 900002fd74fdd3e07eb5592e9541dbcce11b01ec
  jdbc-duckdb.js: 45ca00f4dfdd4b10c4e89657773d1cb5c68d0e43
