author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://github.com/duckdb/duckdb-java. To use it just: loadLib(\"jdbc-duckdb.js\"); var db = new DB(\"jdbc:duckdb:{{file}}\", ...) ");'
keywords:
- DB
- JDBC
- duckdb
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of duckdb
name: jdbc-duckdb
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260618'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- duckdb_jdbc-1.5.4.0.jar
- jdbc-duckdb.js
filesHash:
  LICENSES.txt: 1650ae40675b4e35db1d73163261b651c28f48f9
  duckdb_jdbc-1.5.4.0.jar: 9f8aa5613395699ce8e34b5cb25b247bb1037876
  jdbc-duckdb.js: 45ca00f4dfdd4b10c4e89657773d1cb5c68d0e43
