author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://github.com/couchbaselabs/couchbase-jdbc-driver. To use it just: loadLib(\"jdbc-couchbaseanalytics.js\"); var db = new DB(\"jdbc:couchbase:analytics:{{host}}/{{catalog}}/{{schema}}\", ...) ");'
keywords:
- DB
- JDBC
- couchbaseanalytics
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of couchbaseanalytics
name: jdbc-couchbaseanalytics
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260321'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- couchbase-jdbc-driver-1.1.1.jar
- jdbc-couchbaseanalytics.js
filesHash:
  LICENSES.txt: bd5603a638f1da8d0537705b6e4ea5436ccbd9e8
  couchbase-jdbc-driver-1.1.1.jar: 9fac11a5fcef9881a5e21bc6580b9be7a48b7754
  jdbc-couchbaseanalytics.js: d91da8da46cd77027dd46a0def46732a86abd5c5
