author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://github.com/couchbaselabs/couchbase-jdbc-driver. To use it just: loadLib(\"jdbc-couchbaseanalytics.js\"); var db = new DB(\"jdbc:couchbase:analytics:{{host}}/{{catalog}}/{{schema}}\", ...) ");'
keywords:
- DB
- JDBC
- couchbaseanalytics
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of couchbaseanalytics
name: jdbc-couchbaseanalytics
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260318'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- couchbase-jdbc-driver-1.1.0.jar
- jdbc-couchbaseanalytics.js
filesHash:
  LICENSES.txt: 4b162221a4c37945b667e67fcb9efe154fbf53d0
  couchbase-jdbc-driver-1.1.0.jar: bf9cf60912194a699d86412c312338dfc7f15ee3
  jdbc-couchbaseanalytics.js: d91da8da46cd77027dd46a0def46732a86abd5c5
