author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- prolog
- logic
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  url: https://openaf.io/opacks/prolog.opack
description: Wrapper for the projob library to add prolog functionality.
name: Prolog
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260924'
dependencies:
  openaf: '>=20201111'
files:
- .maven.yaml
- .odoc.db
- .package.yaml
- .precompile
- README.md
- projog-clp-0.3.0.jar
- projog-core-0.12.0.jar
- prolog.js
- prolog.yaml
filesHash:
  .maven.yaml: c6e53f983449d8dda08ff5c13742aaa59ed509e3
  .odoc.db: a216883b46f9c6dd79cba2528c49a876f9d2b2e1
  .precompile: 61adf0138f2b4c4f5a6f4ce1116d1a439e4c9aff
  README.md: 1a6cd939663514ff174c0b864e409f9d53c7b5c3
  projog-clp-0.3.0.jar: 5a46819536cb8c3cef0cfdc85103b46645fd7f6e
  projog-core-0.12.0.jar: f05293a98dcf479837a577712043e12c7dbaf703
  prolog.js: 1f6879ab4412c549f749e7f6e5077977133ae73b
  prolog.yaml: ff4214def94e85120e4da52f7ea8046bd963f552
