todo:
- Update Docsify
- Update PrismJS
- Update Mermaid

ojob:
  async: true

jobs:
# =====================
- name: Update Docsify
  from: Identify files
  each: Download files
  args:
    DIR  : docsify
    URL  : https://unpkg.com/docsify@4.13.1/lib/
    extra:
      "plugins/docsify-copy-code.min.js": https://unpkg.com/docsify-copy-code@3.0.2/dist/docsify-copy-code.min.js
  exec: |
    args._list.map(r => each({ f: r, DIR: args.DIR, URL: args.URL, extra: args.extra }));

# ====================
- name: Update PrismJS
  from: Identify files
  each: Download files
  args:
    DIR: prismjs
    URL: https://unpkg.com/prismjs@1.30.0/components/
    extra:
      "prism.min.js": https://cdnjs.cloudflare.com/ajax/libs/prism/1.30.0/prism.min.js
  exec: |
    args._list.map(r => each({ f: r, DIR: args.DIR, URL: args.URL, extra: args.extra }));

# ====================
- name: Update Mermaid
  from: Identify files
  each: Download files
  args:
    DIR: mermaid
    URL: https://unpkg.com/mermaid@12.0.0/dist/
  exec: |
    args._list.map(r => each({ f: r, DIR: args.DIR, URL: args.URL, extra: args.extra }));


# --------------------
- name: Identify files
  exec: |
    args._list = $from( listFilesRecursive(args.DIR) )
                 .equals("isFile", true)
                 .filter(r => /\.(js|css)$/.test(r.filename))
                 .select(r => r.filepath.replace(new RegExp("^" + args.DIR + "/"), ""));

# ---------------------
- name : Download files
  catch: |
    logErr(stringify(exception));
  exec : |
    var url;

    if (isDef(args.extra) && isDef(args.extra[args.f]))
      url = args.extra[args.f];
    else
      url = args.URL + args.f

    try {
      $rest().get2File(args.DIR + "/" + args.f, url);
      if (/\.css$/.test(args.f)) {
        var file = args.DIR + "/" + args.f;
        io.writeFileString(file, io.readFileString(file).replace(/@import\s+url\("https:\/\/fonts\.googleapis\.com\/[^"\n]*"\);/g, ""));
      }
      log("Downloaded " + args.DIR + "/" + args.f + " <- " + url + "...");
      if (io.fileInfo(args.DIR + "/" + args.f).size == 0) logWarn("Zero sized file "+ args.DIR + "/" + args.f);
    } catch(e) {
      logErr(url + " | " + stringify(e));
    }