author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://github.com/xerial/sqlite-jdbc. To use it just: loadLib(\"jdbc-sqlite.js\"); var db = new DB(\"jdbc:sqlite:{{file}}\", ...) ");'
keywords:
- DB
- JDBC
- sqlite
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of sqlite
name: jdbc-sqlite
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260318'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- jdbc-sqlite.js
- sqlite-jdbc-3.51.3.0.jar
filesHash:
  LICENSES.txt: a0f2897a0c544cab8a614ac7feca38f18223fbb6
  jdbc-sqlite.js: 422313634ed7164995df1635f62c4166b8089250
  sqlite-jdbc-3.51.3.0.jar: a6a5177ff8d35028a8943129aa4a18e850fe1387
