author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- asciinema
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  url: https://openaf.io/opacks/asciinema.opack
description: Asciinema wrapper for use with OpenAF HTTPd server
name: asciinema
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260920'
dependencies:
  openaf: '>=20250713'
files:
- .package.yaml
- README.md
- asciinema.js
- libs/LICENSE
- libs/asciinema-emb-player.js
- libs/asciinema-player.min.css
- libs/asciinema-player.min.js
- upstream.json
filesHash:
  README.md: c7a0e2bd29ddc0d259189320ae94497109a59c34
  asciinema.js: 001caa2c7eb8bfb5ba0c8c5ccdf3f00031d82f22
  libs/LICENSE: 4e7db54f18721e0eb949ebeb51d5da0c6a343877
  libs/asciinema-emb-player.js: 0c375a1327eb0f7eeb99c5cac1d7a824505ab997
  libs/asciinema-player.min.css: 44ea728ebec960b1d6cc3c67a11721bea5358618
  libs/asciinema-player.min.js: 7e9f1b60554266280b23ce3e96390cd4d701f1a3
  upstream.json: 827009b40f1a636a577c74aee124c3c9e80aff20
