// Author: Nuno Aguiar
// AWS Key Management Service

loadLib("aws_core.js")

AWS.prototype._KMS_Call = function(aRegion, anOperation, aParams) {
    aRegion = _$(aRegion).isString().default(this.region)
    anOperation = _$(anOperation, "anOperation").isString().$_()
    aParams = _$(aParams).isMap().default({})

    var aURL = "https://kms." + aRegion + ".amazonaws.com/"
    var url = new java.net.URL(aURL)

    return this.postURLEncoded(aURL, String(url.getPath()), "", aParams, "kms", String(url.getHost()), aRegion, {
        "X-Amz-Target": "TrentService." + anOperation
    }, __, "application/x-amz-json-1.1")
}

AWS.prototype._KMS_ToBase64 = function(aValue) {
    if (isString(aValue)) aValue = af.fromString2Bytes(aValue)
    return af.fromBytes2String(af.toBase64Bytes(aValue))
}

/**
 * <odoc>
 * <key>AWS.KMS_Sign(aRegion, aKeyId, aMessage, aSigningAlgorithm, aMessageType, aGrantTokens) : Map</key>
 * Signs aMessage using an existing asymmetric KMS key. aMessage can be a string or byte array and is encoded for the KMS API.
 * aSigningAlgorithm is, for example, RSASSA_PSS_SHA_256 or ECDSA_SHA_256. aMessageType defaults to RAW and can be DIGEST.
 * Returns the KMS response, including a base64 Signature. Optional aGrantTokens is an array of grant tokens.
 * </odoc>
 */
AWS.prototype.KMS_Sign = function(aRegion, aKeyId, aMessage, aSigningAlgorithm, aMessageType, aGrantTokens) {
    var params = {
        KeyId           : _$(aKeyId, "aKeyId").isString().$_(),
        Message         : this._KMS_ToBase64(aMessage),
        MessageType     : _$(aMessageType).isString().default("RAW"),
        SigningAlgorithm: _$(aSigningAlgorithm, "aSigningAlgorithm").isString().$_()
    }
    if (isArray(aGrantTokens)) params.GrantTokens = aGrantTokens
    return this._KMS_Call(aRegion, "Sign", params)
}

/**
 * <odoc>
 * <key>AWS.KMS_Verify(aRegion, aKeyId, aMessage, aSignature, aSigningAlgorithm, aMessageType, aGrantTokens) : Map</key>
 * Verifies aSignature with an existing asymmetric KMS key. aMessage can be a string or byte array. aSignature must be the base64 value returned by KMS_Sign.
 * aMessageType defaults to RAW and can be DIGEST. Returns a map whose SignatureValid field indicates the result.
 * </odoc>
 */
AWS.prototype.KMS_Verify = function(aRegion, aKeyId, aMessage, aSignature, aSigningAlgorithm, aMessageType, aGrantTokens) {
    var params = {
        KeyId           : _$(aKeyId, "aKeyId").isString().$_(),
        Message         : this._KMS_ToBase64(aMessage),
        MessageType     : _$(aMessageType).isString().default("RAW"),
        Signature       : _$(aSignature, "aSignature").isString().$_(),
        SigningAlgorithm: _$(aSigningAlgorithm, "aSigningAlgorithm").isString().$_()
    }
    if (isArray(aGrantTokens)) params.GrantTokens = aGrantTokens
    return this._KMS_Call(aRegion, "Verify", params)
}

/**
 * <odoc>
 * <key>AWS.KMS_Encrypt(aRegion, aKeyId, aPlaintext, anEncryptionContext, anEncryptionAlgorithm, aGrantTokens) : Map</key>
 * Encrypts string or byte-array aPlaintext using an existing KMS key. Optional anEncryptionContext is a map that must also be supplied to decrypt.
 * anEncryptionAlgorithm defaults to SYMMETRIC_DEFAULT. Returns a map containing the base64 CiphertextBlob.
 * </odoc>
 */
AWS.prototype.KMS_Encrypt = function(aRegion, aKeyId, aPlaintext, anEncryptionContext, anEncryptionAlgorithm, aGrantTokens) {
    var params = {
        KeyId              : _$(aKeyId, "aKeyId").isString().$_(),
        Plaintext          : this._KMS_ToBase64(aPlaintext),
        EncryptionAlgorithm: _$(anEncryptionAlgorithm).isString().default("SYMMETRIC_DEFAULT")
    }
    if (isMap(anEncryptionContext)) params.EncryptionContext = anEncryptionContext
    if (isArray(aGrantTokens)) params.GrantTokens = aGrantTokens
    return this._KMS_Call(aRegion, "Encrypt", params)
}

/**
 * <odoc>
 * <key>AWS.KMS_Decrypt(aRegion, aCiphertextBlob, aKeyId, anEncryptionContext, anEncryptionAlgorithm, aGrantTokens) : Map</key>
 * Decrypts a base64 aCiphertextBlob generated by KMS. aKeyId is optional for symmetric ciphertext but recommended.
 * Optional anEncryptionContext must exactly match the context used to encrypt. Returns a map containing base64 Plaintext.
 * </odoc>
 */
AWS.prototype.KMS_Decrypt = function(aRegion, aCiphertextBlob, aKeyId, anEncryptionContext, anEncryptionAlgorithm, aGrantTokens) {
    var params = {
        CiphertextBlob     : _$(aCiphertextBlob, "aCiphertextBlob").isString().$_(),
        EncryptionAlgorithm: _$(anEncryptionAlgorithm).isString().default("SYMMETRIC_DEFAULT")
    }
    if (isString(aKeyId)) params.KeyId = aKeyId
    if (isMap(anEncryptionContext)) params.EncryptionContext = anEncryptionContext
    if (isArray(aGrantTokens)) params.GrantTokens = aGrantTokens
    return this._KMS_Call(aRegion, "Decrypt", params)
}

/**
 * <odoc>
 * <key>AWS.KMS_DecodeBase64(aValue, asString) : Object</key>
 * Decodes a base64 blob returned by KMS. Returns bytes by default or a UTF-8 string when asString is true.
 * </odoc>
 */
AWS.prototype.KMS_DecodeBase64 = function(aValue, asString) {
    var bytes = af.fromBase64(_$(aValue, "aValue").isString().$_())
    return asString === true ? af.fromBytes2String(bytes) : bytes
}

/**
 * <odoc>
 * <key>AWS.KMS_GetPublicKey(aRegion, aKeyId, aGrantTokens) : Map</key>
 * Returns the public key and supported algorithms for an existing asymmetric KMS key. PublicKey is base64 DER encoded.
 * </odoc>
 */
AWS.prototype.KMS_GetPublicKey = function(aRegion, aKeyId, aGrantTokens) {
    var params = { KeyId: _$(aKeyId, "aKeyId").isString().$_() }
    if (isArray(aGrantTokens)) params.GrantTokens = aGrantTokens
    return this._KMS_Call(aRegion, "GetPublicKey", params)
}

/**
 * <odoc>
 * <key>AWS.KMS_DescribeKey(aRegion, aKeyId, aGrantTokens) : Map</key>
 * Returns metadata for an existing KMS key.
 * </odoc>
 */
AWS.prototype.KMS_DescribeKey = function(aRegion, aKeyId, aGrantTokens) {
    var params = { KeyId: _$(aKeyId, "aKeyId").isString().$_() }
    if (isArray(aGrantTokens)) params.GrantTokens = aGrantTokens
    return this._KMS_Call(aRegion, "DescribeKey", params)
}

/**
 * <odoc>
 * <key>AWS.KMS_GenerateDataKey(aRegion, aKeyId, aKeySpec, anEncryptionContext, aGrantTokens) : Map</key>
 * Generates a data key under an existing symmetric KMS key. aKeySpec defaults to AES_256. Returns base64 Plaintext and CiphertextBlob values.
 * </odoc>
 */
AWS.prototype.KMS_GenerateDataKey = function(aRegion, aKeyId, aKeySpec, anEncryptionContext, aGrantTokens) {
    var params = {
        KeyId : _$(aKeyId, "aKeyId").isString().$_(),
        KeySpec: _$(aKeySpec).isString().default("AES_256")
    }
    if (isMap(anEncryptionContext)) params.EncryptionContext = anEncryptionContext
    if (isArray(aGrantTokens)) params.GrantTokens = aGrantTokens
    return this._KMS_Call(aRegion, "GenerateDataKey", params)
}
