author: OpenAF
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- github
- copilot
- llm
- ai
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  backurl: ''
  url: https://openaf.io/opacks/ghcopilot.opack
description: OpenAF ow.ai provider using copilot-sdk-java.
name: ghcopilot
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260525'
dependencies:
  OpenAF: '>=20260312'
files:
- .maven.yaml
- .package.yaml
- Dockerfile
- README.md
- copilot-sdk-java-1.0.0-beta-java.4.jar
- ghcopilot.js
- jackson-datatype-jsr310-2.21.3.jar
filesHash:
  .maven.yaml: 04eff2e9425c921ccdbae0a377f73d91c4e76c93
  Dockerfile: 6bb1c386f43d37ea2b7f6f1a5dc55f410eb67025
  README.md: 143b909b68d85376ebfcf956c74a8684adacb937
  copilot-sdk-java-1.0.0-beta-java.4.jar: 787bc0bb82f6a4b76da69736bece4cb8d5b0c731
  ghcopilot.js: 4a65ba45ff3546f0b39f69e7dde342c1d643473e
  jackson-datatype-jsr310-2.21.3.jar: a0958ebdaba836d31e5462ebc37b6349a0725ff9
