author: OpenAF
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- github
- copilot
- llm
- ai
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  backurl: ''
  url: https://openaf.io/opacks/ghcopilot.opack
description: OpenAF ow.ai provider using copilot-sdk-java.
name: ghcopilot
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260706'
dependencies:
  OpenAF: '>=20260312'
files:
- .maven.yaml
- .package.yaml
- Dockerfile
- README.md
- copilot-sdk-java-1.0.6-preview.1.jar
- ghcopilot.js
- jackson-datatype-jsr310-2.22.0.jar
filesHash:
  .maven.yaml: 4a70941a8dd2f5ed3d2aa83041652fa7eb508c0f
  Dockerfile: 6bb1c386f43d37ea2b7f6f1a5dc55f410eb67025
  README.md: ff630ffabe4b6d743781fea2d0458ef489d7a6f0
  copilot-sdk-java-1.0.6-preview.1.jar: 6b6d24db4788a073c576a02f406a86ea19b28188
  ghcopilot.js: eacb7f292d776dba36274920378cbc2d76368aec
  jackson-datatype-jsr310-2.22.0.jar: 6aa58b1174d2888ad7f3941e8d9e2fd62775edc3
