author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://www.oracle.com/database/technologies/maven-central-guide.html. To use it just: loadLib(\"jdbc-odbc.js\"); var db = new DB(\"jdbc:odbc:{{db}}\", ...) ");'
keywords:
- DB
- JDBC
- odbc
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of odbc
name: jdbc-odbc
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260513'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- jdbc-odbc.js
- ojdbc8-23.26.2.0.0.jar
filesHash:
  LICENSES.txt: f0891464cba62b6d8a1c81bd084c12203de54f37
  jdbc-odbc.js: 53f00e30b1075b89e793e3d8c1bcb09288898c8d
  ojdbc8-23.26.2.0.0.jar: f347163fed52f09eb36c311ebcc422d6e2facfe8
