author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- Asciidoc
- adoc
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  url: https://openaf.io/opacks/Asciidoc.opack
description: Provides a wrapper around asciidoctor.js enabling conversion to HTML
name: Asciidoc
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260920'
dependencies:
  openaf: '>=20211229'
files:
- .package.yaml
- README.adoc
- asciidoc.js
- lib/HIGHLIGHT-LICENSE
- lib/asciidoctor.css
- lib/asciidoctor.min.js
- lib/highlight.css
- lib/highlight.min.js
- upstream.json
filesHash:
  README.adoc: 75085b108f88970c14f9a026f750be37bbca0eb6
  asciidoc.js: 0a357850b66e894c50e456578fad37e8b5b9e39a
  lib/HIGHLIGHT-LICENSE: 00990dad3f28f5503fad9835bd7291524301574c
  lib/asciidoctor.css: 94ba8057916588bc6e03743d89a9fde4c53ea2d9
  lib/asciidoctor.min.js: 4c7cd7b856b7662f1c20fb3bfb4d78e4bfce9920
  lib/highlight.css: 9dafcb6d23472adb90f9c9f55bd9dbd590392953
  lib/highlight.min.js: c039a299315c3c25be9d66bcdbea3b6af6cf22bc
  upstream.json: fef77375b7aa171ce98dd1239afa360d9a27bfec
