author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://github.com/yugabyte/jdbc-yugabytedb. To use it just: loadLib(\"jdbc-yugabytedb.js\"); var db = new DB(\"jdbc:postgresql://{{host}}:{{port}}/{{database}}\", ...) ");'
keywords:
- DB
- JDBC
- yugabytedb
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of yugabytedb
name: jdbc-yugabytedb
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260920'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- jdbc-yugabytedb-42.7.3-yb-6.jar
- jdbc-yugabytedb.js
filesHash:
  LICENSES.txt: 53372c471c14eebc145129c35f6e38a05859b0f6
  jdbc-yugabytedb-42.7.3-yb-6.jar: bcf8942b569271c2739a2d8d9eca2a67320aa683
  jdbc-yugabytedb.js: 19faaaa5093b34cae6f3566fa150833fac334473
