author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://dev.mysql.com/doc/connector-j/en/connector-j-reference-jdbc-url-format.html. To use it just: loadLib(\"jdbc-mysql.js\"); var db = new DB(\"jdbc:mysql://{{host}}:{{port}}/{{database}}\", ...) ");'
keywords:
- DB
- JDBC
- mysql
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of mysql
name: jdbc-mysql
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260730'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- jdbc-mysql.js
- mysql-connector-j-26.7.0.jar
filesHash:
  LICENSES.txt: f0480a5ff84cb8b7111cc41647f31b61cd5277d7
  jdbc-mysql.js: 9fe06f159e87c01c3b38d10d99d701c2ad82737f
  mysql-connector-j-26.7.0.jar: 43e30438c4c8707272ead3cd3167a1e07abb2c3c
