author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://jdbc.postgresql.org/documentation/head/connect.html. To use it just: loadLib(\"jdbc-postgresql.js\"); var db = new DB(\"jdbc:postgresql://{{host}}:{{port}}/{{database}}\", ...) ");'
keywords:
- DB
- JDBC
- postgresql
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of postgresql
name: jdbc-postgresql
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260707'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- jdbc-postgresql.js
- postgresql-42.7.13.jar
filesHash:
  LICENSES.txt: 62ebee81334a5a2e6e542aa860c1c99d7fe5bd5c
  jdbc-postgresql.js: 6fc8a4ee453c2f0acd20e3981fc93437e4b6ea43
  postgresql-42.7.13.jar: a6e1bd21b412d6ffb3df23cd13d507bc2cc9e37d
