author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://jdbc.postgresql.org/documentation/head/connect.html. To use it just: loadLib(\"jdbc-postgresql.js\"); var db = new DB(\"jdbc:postgresql://{{host}}:{{port}}/{{database}}\", ...) ");'
keywords:
- DB
- JDBC
- postgresql
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of postgresql
name: jdbc-postgresql
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260429'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- jdbc-postgresql.js
- postgresql-42.7.11.jar
filesHash:
  LICENSES.txt: f3eae38a97d6aa907956b2e4d715b59640113738
  jdbc-postgresql.js: 6fc8a4ee453c2f0acd20e3981fc93437e4b6ea43
  postgresql-42.7.11.jar: 4c21cdd1b3938f400703716d37c4e8ca4d332808
