artifacts:
- group: org.apache.tika
  id: tika-core
  version: 4.0.0
- group: org.apache.tika
  id: tika-serialization
  version: 4.0.0
- group: org.apache.tika
  id: tika-parser-pdf-module
  version: 4.0.0
- group: org.apache.tika
  id: tika-parser-microsoft-module
  version: 4.0.0
- group: org.apache.tika
  id: tika-parser-html-module
  version: 4.0.0
- group: org.apache.tika
  id: tika-parser-text-module
  version: 4.0.0
- group: org.apache.tika
  id: tika-parser-mail-module
  version: 4.0.0
- group: org.apache.tika
  id: tika-parser-image-module
  version: 4.0.0
- group: org.apache.tika
  id: tika-parser-ocr-module
  version: 4.0.0
- group: org.apache.tika
  id: tika-parser-zip-commons
  version: 4.0.0
- group: org.apache.logging.log4j
  id: log4j-to-slf4j
  version: 2.26.1
