author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://www.ibm.com/docs/en/db2/11.5?topic=cdsudidsdjs-url-format-data-server-driver-jdbc-sqlj-type-4-connectivity. To use it just: loadLib(\"jdbc-db2.js\"); var db = new DB(\"jdbc:db2://{{server}}:{{port}}/{{database}}\", ...) ");'
keywords:
- DB
- JDBC
- db2
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of db2
name: jdbc-db2
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260627'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- jcc-12.1.5.0.jar
- jdbc-db2.js
filesHash:
  LICENSES.txt: aa1c2052877d092a70dfc90a1c884ea90d37141e
  jcc-12.1.5.0.jar: f549d8e6f78dff153eebec2ed5e67e41744bb690
  jdbc-db2.js: 94579487ff3e381f0f662b2f1e772d900f6ffa4f
