author: ojob.io/db/jdbc
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: 'log("Check https://www.ibm.com/docs/en/db2/11.5?topic=cdsudidsdjs-url-format-data-server-driver-jdbc-sqlj-type-4-connectivity. To use it just: loadLib(\"jdbc-db2.js\"); var db = new DB(\"jdbc:db2://{{server}}:{{port}}/{{database}}\", ...) ");'
keywords:
- DB
- JDBC
- db2
bugs:
  url: URL to track bugs
repository: {}
description: Wrapper for JDBC drivers of db2
name: jdbc-db2
main: ''
mainJob: ''
license: Check the LICENSES.txt file
version: '20260310'
dependencies:
  openaf: '>=20240318'
files:
- .package.yaml
- LICENSES.txt
- jcc-12.1.4.0.jar
- jdbc-db2.js
filesHash:
  LICENSES.txt: 9861cd385bf998a9e11c9b4e09b3146b665602c0
  jcc-12.1.4.0.jar: 1f2041abaf25a76c44fad459c13bc8d717befe11
  jdbc-db2.js: 94579487ff3e381f0f662b2f1e772d900f6ffa4f
