artifacts:
- group: org.apache.kafka
  id: kafka-clients
  version: 4.3.1
- group: org.xerial.snappy
  id: snappy-java
  version: 1.1.10.8
- group: at.yawk.lz4
  id: lz4-java
  version: 1.11.3
- group: com.github.luben
  id: zstd-jni
  version: 1.5.7-17
