author: Nuno Aguiar
scripts:
  preinstall: ''
  postinstall: ''
  preerase: ''
  posterase: ''
keywords:
- kafka
- streaming
- channel
- oafp
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  backurl: https://raw.githubusercontent.com/OpenAF/openaf-opacks/master/Kafka
  url: https://openaf.io/opacks/Kafka.opack
description: Apache Kafka producer and consumer wrapper, stream channel and oafp input/output.
name: Kafka
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260924'
dependencies:
  openaf: '>=20250725'
files:
- .maven.yaml
- .package.yaml
- README.md
- kafka-clients-4.3.1.jar
- kafka.js
- lz4-java-1.11.3.jar
- oafp_kafka.js
- snappy-java-1.1.10.8.jar
- zstd-jni-1.5.7-17.jar
filesHash:
  .maven.yaml: 923859f3e704b63e3d1c5603f13619b205f25f20
  README.md: 874393ef701791c77f5e9832ea7b64fd814752ab
  kafka-clients-4.3.1.jar: 74209a28d36f819b2f7a9b599e468b5654cad514
  kafka.js: ea0484e7b11ed8a5b2df208740a17bb0f0aa0816
  lz4-java-1.11.3.jar: 275ac7e05f6989789004c9faaa4cf64629a29cd9
  oafp_kafka.js: c3e25c37921ea456d20bc817cd6f785d3b6a5993
  snappy-java-1.1.10.8.jar: ccbaa2b5ea6a023a27c44daf2d6cdec0e138592d
  zstd-jni-1.5.7-17.jar: b4fea046fcd925681fa10c61be99da059f4f745a
