author: Nuno Aguiar
scripts:
  preinstall: ''
  postinstall: ''
  preerase: ''
  posterase: ''
keywords:
- kafka
- streaming
- channel
- oafp
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  backurl: https://raw.githubusercontent.com/OpenAF/openaf-opacks/master/Kafka
  url: https://openaf.io/opacks/Kafka.opack
description: Apache Kafka producer and consumer wrapper, stream channel and oafp input/output.
name: Kafka
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20261009'
dependencies:
  openaf: '>=20250725'
files:
- .maven.yaml
- .package.yaml
- README.md
- kafka-clients-4.3.1.jar
- kafka.js
- lz4-java-1.12.0.jar
- oafp_kafka.js
- snappy-java-1.1.10.11.jar
- zstd-jni-1.5.7-22.jar
filesHash:
  .maven.yaml: 687b82d44a53bbb55b7193f79daf7c9d0b7f5b8e
  README.md: bd5f442d11bddcce6ca51771b706afc532d5eb65
  kafka-clients-4.3.1.jar: 74209a28d36f819b2f7a9b599e468b5654cad514
  kafka.js: ea0484e7b11ed8a5b2df208740a17bb0f0aa0816
  lz4-java-1.12.0.jar: 04aeb33effcf8f9e29f4a2e206c224afebd2621d
  oafp_kafka.js: c3e25c37921ea456d20bc817cd6f785d3b6a5993
  snappy-java-1.1.10.11.jar: e633edcf90b86efb17bab87da6ea517933683a88
  zstd-jni-1.5.7-22.jar: 6b2da2ba2a916bd9d89d60bdeede164f989c4b5a
