author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- rocksdb
- rocks
- channels
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  url: https://raw.githubusercontent.com/OpenAF/openaf-opacks/master/rocksdb
description: OpenAF channels wrapper and utilities for RocksDB
name: rocksdb
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260325'
dependencies:
  openaf: '>=20221216'
files:
- .maven.yaml
- .odoc.db
- .package.yaml
- .precompile
- README.md
- rocksdb.js
- rocksdbjni-10.7.5-linux32-musl.jar
- rocksdbjni-10.7.5-linux32.jar
- rocksdbjni-10.7.5-linux64-musl.jar
- rocksdbjni-10.7.5-linux64.jar
- rocksdbjni-10.7.5-osx.jar
- rocksdbjni-10.7.5-win64.jar
- tests/autoTestRocks.js
- tests/autoTestRocks.yaml
filesHash:
  .maven.yaml: 3c819b060ebe7f7cf9ae0ef8f0a7df1d910c55ec
  .odoc.db: 1737cc42c3e23351e5e40bae50dcc8aee5a86d34
  .precompile: b256ffd9d67f0e98a0e3035d7c225e5b444837b5
  README.md: 098d238f3994cb44821651c2d2a8062f69ef5151
  rocksdb.js: 350d3097abeb5012d39a274f3020994a20c39284
  rocksdbjni-10.7.5-linux32-musl.jar: 5c66834888461738e27e2f71494605e2b2e90564
  rocksdbjni-10.7.5-linux32.jar: ede639e7b3dee60d769aa7d35db123eacefe9007
  rocksdbjni-10.7.5-linux64-musl.jar: 6e0a534abecd9691ac98d02c1dca88499e496d5a
  rocksdbjni-10.7.5-linux64.jar: af2a526770c8804491d2bab2a4280312ebae7130
  rocksdbjni-10.7.5-osx.jar: e05173072ea87ca9ea4aaf3d86ebb025b630a7de
  rocksdbjni-10.7.5-win64.jar: 21aef3fe76588598648d84f3ff770e7e2bf7e1d8
  tests/autoTestRocks.js: 0293c08829dd2db5f5d9d3030c613efb2c3773b7
  tests/autoTestRocks.yaml: 930233438b594f1ed9a01e3be2eecba77d1de2f4
