author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- Phone
- Google
- i18n
- Number
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  url: https://openaf.io/opacks/GooglePhoneNumber.opack
description: Provides a wrapper to use the google phone number library (https://github.com/googlei18n/libphonenumber/).
name: GooglePhoneNumber
main: main.js
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260910'
dependencies:
  openaf: '>=20210515'
files:
- .package.yaml
- .precompile
- googlePhoneNumber.js
- googlePhoneNumber.yaml
- lib/LICENSE
- lib/carrier-2.39.jar
- lib/geocoder-3.39.jar
- lib/libphonenumber-9.0.39.jar
- lib/prefixmapper-3.39.jar
- lib/protobuf-javanano-3.0.0-alpha-7.jar
- main.js
- updateGooglePhoneNumber.yaml
filesHash:
  .precompile: 3f9b1bb8aa12e89a9f5a7528f8f27976e4d1fca4
  googlePhoneNumber.js: 0cfd02acaf50f7a16999ac200366c9a52d258a41
  googlePhoneNumber.yaml: 18ae61211a2440ad82e975583756836e7e2ef08d
  lib/LICENSE: a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33
  lib/carrier-2.39.jar: 740c95be08194f587cdbd3fd384df79817466573
  lib/geocoder-3.39.jar: eb35f84a5deb2d7938446ae8a19ccc19b035af86
  lib/libphonenumber-9.0.39.jar: 3b605a0a0ef2f589ea07aaf2790a62429475ef5e
  lib/prefixmapper-3.39.jar: c7474445e2b75c5d6b530a4c0bf76155d1fae49e
  lib/protobuf-javanano-3.0.0-alpha-7.jar: 52587934797e3433992a9d69178a1471e4a8f85d
  main.js: 7a2dc8cd47ee6d46b102418328d74a7243b4fe75
  updateGooglePhoneNumber.yaml: 0da06fa271e5dec1af969bfd0de4af8b236ec5d8
