author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- Redis
- Jedis
bugs:
  url: https://github.com/OpenAF/openaf-opacks/issues
repository:
  type: http
  backurl: https://raw.githubusercontent.com/OpenAF/openaf-opacks/master/Redis
  url: https://openaf.io/opacks/Redis.opack
description: Wrapper to access Redis using the java Jedis client.
name: Redis
main: ''
mainJob: ''
license: https://github.com/OpenAF/openaf-opacks/blob/master/LICENSE
version: '20260817'
dependencies:
  openaf: '>=20250725'
files:
- .maven.yaml
- .odoc.db
- .package.yaml
- .precompile
- README.md
- commons-pool2-2.13.1.jar
- error_prone_annotations-2.48.0.jar
- jedis-8.0.0.jar
- json-20260719.jar
- redis-authx-core-0.1.1-beta2.jar
- redis.js
filesHash:
  .maven.yaml: 34ebd6c2faf25d374f02ebb59a294107319db5df
  .odoc.db: a361200d42fcc7e708fb62afd2ff08d660abc44e
  .precompile: 81b3f5d9f08b3f87e49405c70d13c10c4d7be732
  README.md: 295ddaa3cb4b1f3607c42996c0bfe4788bde8608
  commons-pool2-2.13.1.jar: cf7e8c0242d4c483c42c083b8188ab360ab60f9a
  error_prone_annotations-2.48.0.jar: bbe30942a31d1778c74cb272321267eca82dc708
  jedis-8.0.0.jar: 0e849578cd3d019203aaa12cad5c1f2e0de4eafd
  json-20260719.jar: 82390308e0b67205bf0d0d507dc48e0d71410bf7
  redis-authx-core-0.1.1-beta2.jar: 4037345ff29fb22c737bab2ed116a34262718ae5
  redis.js: c31a2c25d453cacfb0763485c37e3c8d253d82e7
